---
title: "Yuting Vicky Lin Ph.D."
---
***
* 2024~current Postdoctoral researcher in Marine Ecology at [Sesoko Marine Research Station, Tropical Biosphere Research Center, University of the Ryukyus, Japan](https://tbc.skr.u-ryukyu.ac.jp/en/sesoko-station/)

* 2023~2024 Postdoctoral researcher in Marine Ecology at [Institute of Oceanography, National Taiwan University, Taiwan](http://www.oc.ntu.edu.tw/oceng/)

* 2018~2023 PhD in Marine Ecology at [Institute of Oceanography, National Taiwan University, Taiwan](http://www.oc.ntu.edu.tw/oceng/)

* 2016-2018 Master Degree in Marine Ecology at [Institute of Oceanography, National Taiwan University, Taiwan](http://www.oc.ntu.edu.tw/oceng/)

* 2012-2016 Bachelor Degree in Marine Biotechnology at [Department of Marine Biotechnology and Resources, National Sun Yat-sen University, Taiwan](https://mbr.nsysu.edu.tw/?Lang=en)
 
***

I am currently a postdoctoral researcher at the Sesoko Marine Research Station, Tropical Biosphere Research Center, University of the Ryukyus.

I am a marine ecologist specializing in coral-associated ecosystems, including tropical coral reefs, high-latitude marginal reefs, and mesophotic reefs. My research spans population-, community-, and ecosystem-level processes. I am particularly interested in how community structure varies across time and space, how biophysical and anthropogenic drivers shape these communities, and the functional roles they play within their ecosystems. My work encompasses multiple taxonomic groups (e.g., benthic organisms, reef fishes, sea urchins) and employs diverse approaches (e.g., satellite-derived environmental dataset, machine-learning model, and controlled tank experiments) to address these questions.

***

Publications:

1. De Palmas S, Chen Q, Guerbet A, Hsieh YE, Hsu THT, **Lin YV**, Sturaro N, Wang PL, Denis V. Energy acquisition and allocation strategies in scleractinian corals: insights from intraspecific trait variability. Coral Reefs.44:489-500. [Link](https://link.springer.com/article/10.1007/s00338-025-02617-w)

2. **Lin YV**, Chen YL, De Palmas S, Carballo-Bolaños R, Guerbet A, Ribas-Deulofeu L, Tsai CB, Wei Y, Denis V (2024) Rapid shift in benthic assemblages following coral bleaching at an upper mesophotic habitat in Taiwan. Marine Biodiversity. 54: 53. [Link](https://link.springer.com/article/10.1007/s12526-024-01445-5)

3. **Lin YV**, Château PA, Yoko N, Wunderlich RF, Denis V (2024) Drivers of coastal benthic communities in a complex environmental setting. Marine Pollution Bulletin. 203: 116462.[Link](https://www.sciencedirect.com/science/article/pii/S0025326X24004399)

4.	Cannon SE, Donner SD, Liu A, …, **Lin YV**, …, Wilson SK. Macroalgae exhibit diverse responses to human disturbances on coral reefs. Global Change Biology. 29: 3318-3310.
[Link](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.16694)

5.	**Lin YV**, Hsiao WV, W-J Chen, Denis V (2022) Habitat change and its consequences on reef fish specialization in biogeographic transitional zones. Journal of Biogeography. 49:1549-1561. [Link](https://onlinelibrary.wiley.com/doi/full/10.1111/jbi.14450)

6.	De Palmas S, Denis V, Soto, D, **Lin YV**, Ho M-J, Chen CA (2021) Scleractinian diversity in the upper mesophotic zone of Ludao (Taiwan): a museum collection with new records from Taiwanese waters. Marine Biodiversity. 51:1-13. [Link](https://link.springer.com/article/10.1007/s12526-021-01210-y)

7.	Hsiao WV, **Lin YV**, Lin H-T, Denis V (2021) Learning from differences: Abiotic determinism of benthic communities in Northern Taiwan. Marine Environmental Research. 170:105361. [Link](https://www.sciencedirect.com/science/article/pii/S0141113621001173)

8.	Denis V, Fan T-Y, Hsaio WV, Hwang S-J, **Lin YV**, Nozawa Y. (2020) Ideal paper: Tracking the distribution of accretive reef communities across the Kuroshio current. Ecological Research. 35:595-598.  [Link](https://esj-journals.onlinelibrary.wiley.com/doi/full/10.1111/1440-1703.12128?af=R)

9.	**Lin YV**, Denis V. (2019) Acknowledging the differences: number, characteristics, and distribution of marine coastal benthic communities in Taiwan. Ecosphere. 10:e02803.  [Link](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecs2.2803)

10.	Denis V, **Lin YTV**, Ho MJ (2019) A new association between goblet worms (Entoprocta) and xeniid corals (Cnidaria). Marine Biodiversity. 49:487-493. [Link](https://link.springer.com/article/10.1007/s12526-017-0766-4)

11.	Denis V, Chen J-W, Chen Q, Hsieh YE, **Lin YV**, Wang C-W, Wang H-Y, Sturaro N (2019) Biogeography of functional trait diversity in the Taiwanese reef fish fauna. Ecology and Evolution. 9:522–532. 
[Link](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.4771)

Publications in book chapters:

1.	Denis V, Soto D, De Palmas S, **Lin YTV**, Benayahu Y, Huang YM, Liu SL, Chen JW, Chen Q, Sturaro N, Ho M-J, Su Y, Dai CF, Chen CA (2019) Mesophotic coral ecosystems in Taiwan. In: Loya Y, Puglise KA, Bridge T, editors. Mesophotic coral ecosystems of the world. Springer International Publishing AG. 

Publications in scientific magazines:

1.  **Lin  YV**  (2020)  Impact  of  climate  change  on  reef  fish  (In  Chinese).  PanSci 泛 科 學. 
[Link](https://pansci.asia/archives/344996)

2.	**Lin YV** (2020) An underwater garden in the twilight zone - mesophotic coral ecosystem (In Chinese). Science Monthly. 51:70-73. [Link](https://www.scimonth.com.tw/archives/4327)

***
<center>
Last updated: 2025.11.26
</center>
